"""
Custom Middleware Data-Transformation Engine.

This script acts as middleware translating flat Monday.com style B2B sales records
(such as those generated by data_simulation.py) into the strict, nested structural
layout required by Xero's /Invoices API endpoint.

It features:
- A Data Validation Layer checking for missing or invalid parameters.
- Structural mapping to Xero Invoice and Contact objects.
- Multi-line transaction grouping (consolidation by company).
- Detailed structured error payloads for invalid records.

All variable naming, logging, and documentation conform strictly to UK English.
"""

import argparse
import json
import logging
import re
import sys
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Tuple

# Logging configuration in UK English
logger = logging.getLogger("XeroTransactionTransformer")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)

# Basic email validation regex
EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$")


class XeroTransactionTransformer:
    """
    Middleware engine parsing, validating, and converting flat transaction feeds
    into strict Xero Invoices.
    """

    def __init__(self, default_account_code: str = "200"):
        """
        Initialise the transformer.

        Args:
            default_account_code: The standard Xero Account Code for sales line items.
        """
        self.default_account_code = default_account_code
        logger.info("XeroTransactionTransformer engine initialised.")

    def validate_record(self, record: Dict[str, Any]) -> List[str]:
        """
        Active Data Validation Layer. Checks incoming flat JSON payloads for completeness
        and datatype validity.

        Args:
            record: The flat transaction record to validate.

        Returns:
            A list of validation error descriptions. If empty, the record is valid.
        """
        errors = []

        # Check required fields presence
        required_fields = [
            "transaction_id",
            "customer_first_name",
            "customer_last_name",
            "company_name",
            "email_address",
            "item_description",
            "quantity",
            "unit_price",
            "target_date"
        ]
        
        for field in required_fields:
            if field not in record or record[field] is None:
                errors.append(f"Missing required field: '{field}'")
                continue

            # Check for empty strings in string fields
            if isinstance(record[field], str) and not record[field].strip():
                errors.append(f"Field '{field}' cannot be blank")

        if errors:
            # Return early if fundamental keys are missing to avoid TypeErrors
            return errors

        # Validate email format
        email = record["email_address"]
        if not EMAIL_REGEX.match(email):
            errors.append(f"Invalid email_address format: '{email}'")

        # Validate numeric quantities
        qty = record["quantity"]
        if not isinstance(qty, int) or qty <= 0:
            errors.append(f"Quantity must be a positive integer, got: {qty}")

        # Validate unit price
        price = record["unit_price"]
        if not isinstance(price, (int, float)) or price <= 0:
            errors.append(f"Unit price must be a positive number, got: {price}")

        # Validate date string format
        date_str = record["target_date"].rstrip("Z")
        try:
            datetime.fromisoformat(date_str)
        except ValueError:
            errors.append(f"Invalid ISO 8601 target_date string: '{record['target_date']}'")

        return errors

    def transform_single(
        self,
        record: Dict[str, Any],
        status: str = "DRAFT"
    ) -> Dict[str, Any]:
        """
        Transform a single flat transaction record. Performs validation first.
        If validation fails, returns a structured error payload.

        Args:
            record: Flat transaction dictionary.
            status: Target Xero invoice status.

        Returns:
            A dictionary containing a success status and the mapped Xero invoice,
            or a failure status with a list of validation errors.
        """
        validation_errors = self.validate_record(record)
        
        if validation_errors:
            logger.warning(
                "Validation failed for record %s: %s",
                record.get("transaction_id", "unknown"),
                ", ".join(validation_errors)
            )
            return {
                "status": "validation_failed",
                "record_id": record.get("transaction_id", "unknown"),
                "validation_errors": validation_errors,
                "original_record": record
            }

        # Date transformations
        target_date_str = record["target_date"].rstrip("Z")
        date_parsed = datetime.fromisoformat(target_date_str)
        date_formatted = date_parsed.strftime("%Y-%m-%d")
        due_date_formatted = (date_parsed + timedelta(days=30)).strftime("%Y-%m-%d")

        mapped_invoice = {
            "Type": "ACCREC",
            "Contact": {
                "Name": record["company_name"],
                "FirstName": record["customer_first_name"],
                "LastName": record["customer_last_name"],
                "EmailAddress": record["email_address"]
            },
            "Date": date_formatted,
            "DueDate": due_date_formatted,
            "Reference": f"TX-{record['transaction_id'][:8]}",
            "LineItems": [
                {
                    "Description": record["item_description"],
                    "Quantity": record["quantity"],
                    "UnitAmount": record["unit_price"],
                    "AccountCode": self.default_account_code
                }
            ],
            "Status": status
        }

        return {
            "status": "success",
            "invoice": mapped_invoice
        }

    def transform_batch_grouped(
        self,
        records: List[Dict[str, Any]],
        status: str = "DRAFT"
    ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
        """
        Transform multiple flat records, grouping items by company to produce
        multi-line invoices.

        If a record fails validation, it is separated into the errors list.

        Args:
            records: List of flat transaction records.
            status: Target Xero invoice status.

        Returns:
            A tuple of (list of mapped Xero invoices, list of structured error payloads).
        """
        grouped_transactions: Dict[str, List[Dict[str, Any]]] = {}
        validation_failures: List[Dict[str, Any]] = []

        # Validate and group records by company name
        for record in records:
            errors = self.validate_record(record)
            if errors:
                validation_failures.append({
                    "status": "validation_failed",
                    "record_id": record.get("transaction_id", "unknown"),
                    "validation_errors": errors,
                    "original_record": record
                })
            else:
                company = record["company_name"]
                if company not in grouped_transactions:
                    grouped_transactions[company] = []
                grouped_transactions[company].append(record)

        transformed_invoices: List[Dict[str, Any]] = []

        # Construct multi-line invoices from the grouped records
        for company, tx_list in grouped_transactions.items():
            # Use the first transaction's customer details to construct the Xero Contact
            primary_tx = tx_list[0]
            
            # Find the earliest transaction date in the group to use as invoice date
            parsed_dates = []
            for tx in tx_list:
                dt_str = tx["target_date"].rstrip("Z")
                parsed_dates.append(datetime.fromisoformat(dt_str))
            
            earliest_date = min(parsed_dates)
            date_formatted = earliest_date.strftime("%Y-%m-%d")
            due_date_formatted = (earliest_date + timedelta(days=30)).strftime("%Y-%m-%d")

            # Compile line items for all transactions in this company group
            line_items = []
            for tx in tx_list:
                line_items.append({
                    "Description": tx["item_description"],
                    "Quantity": tx["quantity"],
                    "UnitAmount": tx["unit_price"],
                    "AccountCode": self.default_account_code
                })

            invoice = {
                "Type": "ACCREC",
                "Contact": {
                    "Name": company,
                    "FirstName": primary_tx["customer_first_name"],
                    "LastName": primary_tx["customer_last_name"],
                    "EmailAddress": primary_tx["email_address"]
                },
                "Date": date_formatted,
                "DueDate": due_date_formatted,
                "Reference": f"TX-GRP-{primary_tx['transaction_id'][:8]}",
                "LineItems": line_items,
                "Status": status
            }

            transformed_invoices.append(invoice)

        logger.info(
            "Batch transformation finished. Mapped %d multi-line invoices. Rejected %d invalid records.",
            len(transformed_invoices),
            len(validation_failures)
        )

        return transformed_invoices, validation_failures


def main():
    """CLI execution entrypoint."""
    parser = argparse.ArgumentParser(
        description="Middleware parsing flat Monday.com files to nested Xero Invoice JSON payloads."
    )
    parser.add_argument(
        "--input-file",
        type=str,
        default="transactions_simulation.json",
        help="JSON file containing the simulated B2B sales records (default: transactions_simulation.json)"
    )
    parser.add_argument(
        "--output-file",
        type=str,
        default="transformed_invoices.json",
        help="Output target for the transformed Xero Invoices (default: transformed_invoices.json)"
    )
    parser.add_argument(
        "--group",
        action="store_true",
        help="Enable B2B batch grouping (consolidates records for the same company into multi-line invoices)"
    )
    parser.add_argument(
        "--status",
        choices=["DRAFT", "SUBMITTED", "AUTHORISED"],
        default="DRAFT",
        help="Invoice status to assign (default: DRAFT)"
    )
    parser.add_argument(
        "--account-code",
        type=str,
        default="200",
        help="Default Xero Chart of Accounts code for sales items (default: 200)"
    )

    args = parser.parse_args()

    # Load input transactions
    try:
        with open(args.input_file, "r", encoding="utf-8") as f:
            records = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Error: Failed to load input file: {e}", file=sys.stderr)
        sys.exit(1)

    # Ensure we are handling a list
    if not isinstance(records, list):
        records = [records]

    transformer = XeroTransactionTransformer(default_account_code=args.account_code)

    if args.group:
        # Grouping Mode: yields multi-line invoices
        invoices, errors = transformer.transform_batch_grouped(records, status=args.status)
        output_payload = {
            "transformed_invoices": invoices,
            "failed_records": errors
        }
    else:
        # Single Mode: yields one-to-one mapped success/failure results
        invoices = []
        errors = []
        for record in records:
            result = transformer.transform_single(record, status=args.status)
            if result["status"] == "success":
                invoices.append(result["invoice"])
            else:
                errors.append(result)
        
        output_payload = {
            "transformed_invoices": invoices,
            "failed_records": errors
        }

    # Save outputs
    try:
        with open(args.output_file, "w", encoding="utf-8") as f:
            json.dump(output_payload, f, indent=4)
        print(
            f"Successfully processed {len(records)} records.\n"
            f"Saved {len(invoices)} invoices and {len(errors)} validation errors to {args.output_file}",
            file=sys.stderr
        )
    except OSError as e:
        print(f"Error: Failed to save transformed outputs: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
